language: "python"

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "pypy"
   - "pypy3"

install:
   - pip install flake8

script:
   - flake8 --ignore=W191,F401,E501 .

notifications:
  email:
    on_success: change
    on_failure: always
