language: "python"

sudo: required

services:
   - postgresql

env:
   - PGVERSION=9.5
   - PGVERSION=9.6

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "pypy"
   - "pypy3"

before_install:
   - packages="postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-common"
   - wget https://raw.githubusercontent.com/postgrespro/pg_pathman/master/travis/apt.postgresql.org.sh
   - sudo sh ./apt.postgresql.org.sh

install:
   - sudo apt-get update
   - sudo service postgresql stop
   - echo 'exit 0' | sudo tee /etc/init.d/postgresql
   - sudo chmod a+x /etc/init.d/postgresql
   - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $packages

before_script:
   - sudo pg_createcluster --start $PGVERSION testgres -- -A trust
   - sudo chmod a+w /var/run/postgresql/
   - sudo /etc/init.d/postgresql restart
   - export PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
   - virtualenv /tmp/envs/testgres
   - source /tmp/envs/testgres/bin/activate
   - pip install six psycopg2 pg8000 flake8
   - python setup.py install

script:
   - cd testgres/tests
   - python -m unittest test_simple
   - flake8 --ignore=W191,F401,E501,F403 .

notifications:
  email:
    on_success: change
    on_failure: always
